### ISSUE TITLE
Multi source Python version?

### ISSUE THREAD

**Issue by bbartling** [OpenVINO-dev-contest/decode-infer-on-GPU#1]
Hi @OpenVINO-dev-contest could there ever be a multi-source Python version for GPU? Also curious if Yolov7 can be used too?

Else it could be a good reason for me to pickup C++ : )

**Comment by openvino-dev-samples** [comment]
Yes Python can do the same thing except the remote-tensor which is used to share GPU memory on decoding's output and inference's input. 

I think the best method to implement this pipeline in Python is use [dlstreamer](https://github.com/dlstreamer/dlstreamer) which is more like the gstreamer with openvino inference

**Comment by bbartling** [comment]
Super cool...could I ever trouble you to get off the ground in Python for what you described? Am hoping to build around the whole IoT concept idea...and what else would be really neat as well if for dev purposes run on Ubuntu CPU until I can get a GPU machine with the defined hardware requirements in this repo.

**Comment by openvino-dev-samples** [comment]
I find a python samples for multi-source capture, maybe you directly use some modules from it.
https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/multi_camera_multi_target_tracking_demo/python

**Comment by bbartling** [comment]
Could I ever try out your cpp version on CPU for testing purposes? Am trying the Python version in the link you sent but running into some issues and support seems really slow or not available.

**Comment by openvino-dev-samples** [comment]
If you have iGPU along with your CPU, yes. if not, this sample will not work for CPU alone.
